#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gedit
Version  : 3.32.0
Release  : 25
URL      : https://download.gnome.org/sources/gedit/3.32/gedit-3.32.0.tar.xz
Source0  : https://download.gnome.org/sources/gedit/3.32/gedit-3.32.0.tar.xz
Summary  : GNOME Text Editor
Group    : Development/Tools
License  : GPL-2.0
Requires: gedit-bin = %{version}-%{release}
Requires: gedit-data = %{version}-%{release}
Requires: gedit-lib = %{version}-%{release}
Requires: gedit-libexec = %{version}-%{release}
Requires: gedit-license = %{version}-%{release}
Requires: gedit-locales = %{version}-%{release}
Requires: gedit-man = %{version}-%{release}
Requires: gedit-python = %{version}-%{release}
Requires: gedit-python3 = %{version}-%{release}
BuildRequires : appstream-glib
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gdk-pixbuf
BuildRequires : gspell-dev
BuildRequires : gtk-doc-dev
BuildRequires : gtksourceview-dev
BuildRequires : itstool
BuildRequires : libpeas-dev
BuildRequires : libsoup-dev
BuildRequires : vala
Patch1: cve-2017-14108.nopatch

%description
=====
libgd
=====
Introduction
============
libgd is a library used by various GNOME 3 styled applications.
However, it is not a typical library, since it doesn't guarantee
API/ABI stability, nor does it has official releases tarballs. Only
the files actually used by your project will be shipped with its
tarball. Only the necessary dependencies will be checked during
configure time and used at runtime.

%package bin
Summary: bin components for the gedit package.
Group: Binaries
Requires: gedit-data = %{version}-%{release}
Requires: gedit-libexec = %{version}-%{release}
Requires: gedit-license = %{version}-%{release}

%description bin
bin components for the gedit package.


%package data
Summary: data components for the gedit package.
Group: Data

%description data
data components for the gedit package.


%package dev
Summary: dev components for the gedit package.
Group: Development
Requires: gedit-lib = %{version}-%{release}
Requires: gedit-bin = %{version}-%{release}
Requires: gedit-data = %{version}-%{release}
Provides: gedit-devel = %{version}-%{release}
Requires: gedit = %{version}-%{release}

%description dev
dev components for the gedit package.


%package doc
Summary: doc components for the gedit package.
Group: Documentation
Requires: gedit-man = %{version}-%{release}

%description doc
doc components for the gedit package.


%package lib
Summary: lib components for the gedit package.
Group: Libraries
Requires: gedit-data = %{version}-%{release}
Requires: gedit-libexec = %{version}-%{release}
Requires: gedit-license = %{version}-%{release}

%description lib
lib components for the gedit package.


%package libexec
Summary: libexec components for the gedit package.
Group: Default
Requires: gedit-license = %{version}-%{release}

%description libexec
libexec components for the gedit package.


%package license
Summary: license components for the gedit package.
Group: Default

%description license
license components for the gedit package.


%package locales
Summary: locales components for the gedit package.
Group: Default

%description locales
locales components for the gedit package.


%package man
Summary: man components for the gedit package.
Group: Default

%description man
man components for the gedit package.


%package python
Summary: python components for the gedit package.
Group: Default
Requires: gedit-python3 = %{version}-%{release}

%description python
python components for the gedit package.


%package python3
Summary: python3 components for the gedit package.
Group: Default
Requires: python3-core

%description python3
python3 components for the gedit package.


%prep
%setup -q -n gedit-3.32.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552318040
export LDFLAGS="${LDFLAGS} -fno-lto"
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gedit
cp COPYING %{buildroot}/usr/share/package-licenses/gedit/COPYING
cp win32/installer/COPYING.rtf %{buildroot}/usr/share/package-licenses/gedit/win32_installer_COPYING.rtf
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gedit

%files
%defattr(-,root,root,-)
/usr/lib64/gedit/girepository-1.0/Gedit-3.0.typelib
/usr/lib64/gedit/plugins/docinfo.plugin
/usr/lib64/gedit/plugins/externaltools.plugin
/usr/lib64/gedit/plugins/externaltools/__init__.py
/usr/lib64/gedit/plugins/externaltools/appactivatable.py
/usr/lib64/gedit/plugins/externaltools/capture.py
/usr/lib64/gedit/plugins/externaltools/filelookup.py
/usr/lib64/gedit/plugins/externaltools/functions.py
/usr/lib64/gedit/plugins/externaltools/library.py
/usr/lib64/gedit/plugins/externaltools/linkparsing.py
/usr/lib64/gedit/plugins/externaltools/manager.py
/usr/lib64/gedit/plugins/externaltools/outputpanel.py
/usr/lib64/gedit/plugins/externaltools/windowactivatable.py
/usr/lib64/gedit/plugins/filebrowser.plugin
/usr/lib64/gedit/plugins/modelines.plugin
/usr/lib64/gedit/plugins/pythonconsole.plugin
/usr/lib64/gedit/plugins/pythonconsole/__init__.py
/usr/lib64/gedit/plugins/pythonconsole/config.py
/usr/lib64/gedit/plugins/pythonconsole/console.py
/usr/lib64/gedit/plugins/quickhighlight.plugin
/usr/lib64/gedit/plugins/quickopen.plugin
/usr/lib64/gedit/plugins/quickopen/__init__.py
/usr/lib64/gedit/plugins/quickopen/popup.py
/usr/lib64/gedit/plugins/quickopen/virtualdirs.py
/usr/lib64/gedit/plugins/snippets.plugin
/usr/lib64/gedit/plugins/snippets/__init__.py
/usr/lib64/gedit/plugins/snippets/appactivatable.py
/usr/lib64/gedit/plugins/snippets/completion.py
/usr/lib64/gedit/plugins/snippets/document.py
/usr/lib64/gedit/plugins/snippets/exporter.py
/usr/lib64/gedit/plugins/snippets/helper.py
/usr/lib64/gedit/plugins/snippets/importer.py
/usr/lib64/gedit/plugins/snippets/languagemanager.py
/usr/lib64/gedit/plugins/snippets/library.py
/usr/lib64/gedit/plugins/snippets/manager.py
/usr/lib64/gedit/plugins/snippets/parser.py
/usr/lib64/gedit/plugins/snippets/placeholder.py
/usr/lib64/gedit/plugins/snippets/shareddata.py
/usr/lib64/gedit/plugins/snippets/signals.py
/usr/lib64/gedit/plugins/snippets/singleton.py
/usr/lib64/gedit/plugins/snippets/snippet.py
/usr/lib64/gedit/plugins/snippets/substitutionparser.py
/usr/lib64/gedit/plugins/snippets/windowactivatable.py
/usr/lib64/gedit/plugins/sort.plugin
/usr/lib64/gedit/plugins/spell.plugin
/usr/lib64/gedit/plugins/time.plugin

%files bin
%defattr(-,root,root,-)
/usr/bin/gedit

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnome.gedit.desktop
/usr/share/dbus-1/services/org.gnome.gedit.service
/usr/share/gedit/gir-1.0/Gedit-3.0.gir
/usr/share/gedit/plugins/externaltools/tools/build
/usr/share/gedit/plugins/externaltools/tools/open-terminal-here
/usr/share/gedit/plugins/externaltools/tools/remove-trailing-spaces
/usr/share/gedit/plugins/externaltools/tools/run-command
/usr/share/gedit/plugins/externaltools/tools/send-to-fpaste
/usr/share/gedit/plugins/externaltools/ui/outputpanel.ui
/usr/share/gedit/plugins/externaltools/ui/tools.ui
/usr/share/gedit/plugins/modelines/language-mappings
/usr/share/gedit/plugins/pythonconsole/ui/config.ui
/usr/share/gedit/plugins/snippets/c.xml
/usr/share/gedit/plugins/snippets/chdr.xml
/usr/share/gedit/plugins/snippets/cpp.xml
/usr/share/gedit/plugins/snippets/css.xml
/usr/share/gedit/plugins/snippets/docbook.xml
/usr/share/gedit/plugins/snippets/fortran.xml
/usr/share/gedit/plugins/snippets/global.xml
/usr/share/gedit/plugins/snippets/haskell.xml
/usr/share/gedit/plugins/snippets/html.xml
/usr/share/gedit/plugins/snippets/idl.xml
/usr/share/gedit/plugins/snippets/java.xml
/usr/share/gedit/plugins/snippets/javascript.xml
/usr/share/gedit/plugins/snippets/lang/snippets.lang
/usr/share/gedit/plugins/snippets/latex.xml
/usr/share/gedit/plugins/snippets/mallard.xml
/usr/share/gedit/plugins/snippets/markdown.xml
/usr/share/gedit/plugins/snippets/perl.xml
/usr/share/gedit/plugins/snippets/php.xml
/usr/share/gedit/plugins/snippets/python.xml
/usr/share/gedit/plugins/snippets/rpmspec.xml
/usr/share/gedit/plugins/snippets/ruby.xml
/usr/share/gedit/plugins/snippets/sh.xml
/usr/share/gedit/plugins/snippets/snippets.xml
/usr/share/gedit/plugins/snippets/tcl.xml
/usr/share/gedit/plugins/snippets/ui/snippets.ui
/usr/share/gedit/plugins/snippets/xml.xml
/usr/share/gedit/plugins/snippets/xslt.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.plugins.externaltools.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.plugins.filebrowser.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.plugins.filebrowser.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.plugins.pythonconsole.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.plugins.time.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.plugins.time.gschema.xml
/usr/share/icons/hicolor/scalable/apps/org.gnome.gedit.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.gedit-symbolic.svg
/usr/share/metainfo/org.gnome.gedit.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/gedit-3.14/gedit/gedit-app-activatable.h
/usr/include/gedit-3.14/gedit/gedit-app.h
/usr/include/gedit-3.14/gedit/gedit-commands.h
/usr/include/gedit-3.14/gedit/gedit-debug.h
/usr/include/gedit-3.14/gedit/gedit-document.h
/usr/include/gedit-3.14/gedit/gedit-encodings-combo-box.h
/usr/include/gedit-3.14/gedit/gedit-menu-extension.h
/usr/include/gedit-3.14/gedit/gedit-message-bus.h
/usr/include/gedit-3.14/gedit/gedit-message.h
/usr/include/gedit-3.14/gedit/gedit-progress-info-bar.h
/usr/include/gedit-3.14/gedit/gedit-statusbar.h
/usr/include/gedit-3.14/gedit/gedit-tab.h
/usr/include/gedit-3.14/gedit/gedit-utils.h
/usr/include/gedit-3.14/gedit/gedit-view-activatable.h
/usr/include/gedit-3.14/gedit/gedit-view.h
/usr/include/gedit-3.14/gedit/gedit-window-activatable.h
/usr/include/gedit-3.14/gedit/gedit-window.h
/usr/lib64/pkgconfig/gedit.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/gedit/figures/gedit-html-snippet.png
/usr/share/help/C/gedit/figures/gedit-icon.png
/usr/share/help/C/gedit/figures/gedit3-screenshot.png
/usr/share/help/C/gedit/gedit-change-color-scheme.page
/usr/share/help/C/gedit/gedit-change-default-font.page
/usr/share/help/C/gedit/gedit-close-file.page
/usr/share/help/C/gedit/gedit-create-new-file.page
/usr/share/help/C/gedit/gedit-edit-as-root.page
/usr/share/help/C/gedit/gedit-files-basic.page
/usr/share/help/C/gedit/gedit-full-screen.page
/usr/share/help/C/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/C/gedit/gedit-open-files.page
/usr/share/help/C/gedit/gedit-open-on-server.page
/usr/share/help/C/gedit/gedit-open-recent.page
/usr/share/help/C/gedit/gedit-plugin-guide.page
/usr/share/help/C/gedit/gedit-plugins-change-case.page
/usr/share/help/C/gedit/gedit-plugins-doc-stats.page
/usr/share/help/C/gedit/gedit-plugins-external-tools.page
/usr/share/help/C/gedit/gedit-plugins-file-browser.page
/usr/share/help/C/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/C/gedit/gedit-plugins-install.page
/usr/share/help/C/gedit/gedit-plugins-modelines.page
/usr/share/help/C/gedit/gedit-plugins-pyconsole.page
/usr/share/help/C/gedit/gedit-plugins-quick-open.page
/usr/share/help/C/gedit/gedit-plugins-snippets.page
/usr/share/help/C/gedit/gedit-plugins-sort.page
/usr/share/help/C/gedit/gedit-printing-order.page
/usr/share/help/C/gedit/gedit-printing-select.page
/usr/share/help/C/gedit/gedit-printing.page
/usr/share/help/C/gedit/gedit-quickstart.page
/usr/share/help/C/gedit/gedit-replace.page
/usr/share/help/C/gedit/gedit-save-file.page
/usr/share/help/C/gedit/gedit-search.page
/usr/share/help/C/gedit/gedit-shortcut-keys.page
/usr/share/help/C/gedit/gedit-spellcheck.page
/usr/share/help/C/gedit/gedit-syntax-highlighting.page
/usr/share/help/C/gedit/gedit-tab-groups.page
/usr/share/help/C/gedit/gedit-tabs-moving.page
/usr/share/help/C/gedit/gedit-tabs.page
/usr/share/help/C/gedit/gedit-undo-recent-action.page
/usr/share/help/C/gedit/index.page
/usr/share/help/C/gedit/legal.xml
/usr/share/help/ar/gedit/figures/gedit-html-snippet.png
/usr/share/help/ar/gedit/figures/gedit-icon.png
/usr/share/help/ar/gedit/figures/gedit3-screenshot.png
/usr/share/help/ar/gedit/gedit-change-color-scheme.page
/usr/share/help/ar/gedit/gedit-change-default-font.page
/usr/share/help/ar/gedit/gedit-close-file.page
/usr/share/help/ar/gedit/gedit-create-new-file.page
/usr/share/help/ar/gedit/gedit-edit-as-root.page
/usr/share/help/ar/gedit/gedit-files-basic.page
/usr/share/help/ar/gedit/gedit-full-screen.page
/usr/share/help/ar/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/ar/gedit/gedit-open-files.page
/usr/share/help/ar/gedit/gedit-open-on-server.page
/usr/share/help/ar/gedit/gedit-open-recent.page
/usr/share/help/ar/gedit/gedit-plugin-guide.page
/usr/share/help/ar/gedit/gedit-plugins-change-case.page
/usr/share/help/ar/gedit/gedit-plugins-doc-stats.page
/usr/share/help/ar/gedit/gedit-plugins-external-tools.page
/usr/share/help/ar/gedit/gedit-plugins-file-browser.page
/usr/share/help/ar/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/ar/gedit/gedit-plugins-install.page
/usr/share/help/ar/gedit/gedit-plugins-modelines.page
/usr/share/help/ar/gedit/gedit-plugins-pyconsole.page
/usr/share/help/ar/gedit/gedit-plugins-quick-open.page
/usr/share/help/ar/gedit/gedit-plugins-snippets.page
/usr/share/help/ar/gedit/gedit-plugins-sort.page
/usr/share/help/ar/gedit/gedit-printing-order.page
/usr/share/help/ar/gedit/gedit-printing-select.page
/usr/share/help/ar/gedit/gedit-printing.page
/usr/share/help/ar/gedit/gedit-quickstart.page
/usr/share/help/ar/gedit/gedit-replace.page
/usr/share/help/ar/gedit/gedit-save-file.page
/usr/share/help/ar/gedit/gedit-search.page
/usr/share/help/ar/gedit/gedit-shortcut-keys.page
/usr/share/help/ar/gedit/gedit-spellcheck.page
/usr/share/help/ar/gedit/gedit-syntax-highlighting.page
/usr/share/help/ar/gedit/gedit-tab-groups.page
/usr/share/help/ar/gedit/gedit-tabs-moving.page
/usr/share/help/ar/gedit/gedit-tabs.page
/usr/share/help/ar/gedit/gedit-undo-recent-action.page
/usr/share/help/ar/gedit/index.page
/usr/share/help/ar/gedit/legal.xml
/usr/share/help/bg/gedit/figures/gedit-html-snippet.png
/usr/share/help/bg/gedit/figures/gedit-icon.png
/usr/share/help/bg/gedit/figures/gedit3-screenshot.png
/usr/share/help/bg/gedit/gedit-change-color-scheme.page
/usr/share/help/bg/gedit/gedit-change-default-font.page
/usr/share/help/bg/gedit/gedit-close-file.page
/usr/share/help/bg/gedit/gedit-create-new-file.page
/usr/share/help/bg/gedit/gedit-edit-as-root.page
/usr/share/help/bg/gedit/gedit-files-basic.page
/usr/share/help/bg/gedit/gedit-full-screen.page
/usr/share/help/bg/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/bg/gedit/gedit-open-files.page
/usr/share/help/bg/gedit/gedit-open-on-server.page
/usr/share/help/bg/gedit/gedit-open-recent.page
/usr/share/help/bg/gedit/gedit-plugin-guide.page
/usr/share/help/bg/gedit/gedit-plugins-change-case.page
/usr/share/help/bg/gedit/gedit-plugins-doc-stats.page
/usr/share/help/bg/gedit/gedit-plugins-external-tools.page
/usr/share/help/bg/gedit/gedit-plugins-file-browser.page
/usr/share/help/bg/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/bg/gedit/gedit-plugins-install.page
/usr/share/help/bg/gedit/gedit-plugins-modelines.page
/usr/share/help/bg/gedit/gedit-plugins-pyconsole.page
/usr/share/help/bg/gedit/gedit-plugins-quick-open.page
/usr/share/help/bg/gedit/gedit-plugins-snippets.page
/usr/share/help/bg/gedit/gedit-plugins-sort.page
/usr/share/help/bg/gedit/gedit-printing-order.page
/usr/share/help/bg/gedit/gedit-printing-select.page
/usr/share/help/bg/gedit/gedit-printing.page
/usr/share/help/bg/gedit/gedit-quickstart.page
/usr/share/help/bg/gedit/gedit-replace.page
/usr/share/help/bg/gedit/gedit-save-file.page
/usr/share/help/bg/gedit/gedit-search.page
/usr/share/help/bg/gedit/gedit-shortcut-keys.page
/usr/share/help/bg/gedit/gedit-spellcheck.page
/usr/share/help/bg/gedit/gedit-syntax-highlighting.page
/usr/share/help/bg/gedit/gedit-tab-groups.page
/usr/share/help/bg/gedit/gedit-tabs-moving.page
/usr/share/help/bg/gedit/gedit-tabs.page
/usr/share/help/bg/gedit/gedit-undo-recent-action.page
/usr/share/help/bg/gedit/index.page
/usr/share/help/bg/gedit/legal.xml
/usr/share/help/ca/gedit/figures/gedit-html-snippet.png
/usr/share/help/ca/gedit/figures/gedit-icon.png
/usr/share/help/ca/gedit/figures/gedit3-screenshot.png
/usr/share/help/ca/gedit/gedit-change-color-scheme.page
/usr/share/help/ca/gedit/gedit-change-default-font.page
/usr/share/help/ca/gedit/gedit-close-file.page
/usr/share/help/ca/gedit/gedit-create-new-file.page
/usr/share/help/ca/gedit/gedit-edit-as-root.page
/usr/share/help/ca/gedit/gedit-files-basic.page
/usr/share/help/ca/gedit/gedit-full-screen.page
/usr/share/help/ca/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/ca/gedit/gedit-open-files.page
/usr/share/help/ca/gedit/gedit-open-on-server.page
/usr/share/help/ca/gedit/gedit-open-recent.page
/usr/share/help/ca/gedit/gedit-plugin-guide.page
/usr/share/help/ca/gedit/gedit-plugins-change-case.page
/usr/share/help/ca/gedit/gedit-plugins-doc-stats.page
/usr/share/help/ca/gedit/gedit-plugins-external-tools.page
/usr/share/help/ca/gedit/gedit-plugins-file-browser.page
/usr/share/help/ca/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/ca/gedit/gedit-plugins-install.page
/usr/share/help/ca/gedit/gedit-plugins-modelines.page
/usr/share/help/ca/gedit/gedit-plugins-pyconsole.page
/usr/share/help/ca/gedit/gedit-plugins-quick-open.page
/usr/share/help/ca/gedit/gedit-plugins-snippets.page
/usr/share/help/ca/gedit/gedit-plugins-sort.page
/usr/share/help/ca/gedit/gedit-printing-order.page
/usr/share/help/ca/gedit/gedit-printing-select.page
/usr/share/help/ca/gedit/gedit-printing.page
/usr/share/help/ca/gedit/gedit-quickstart.page
/usr/share/help/ca/gedit/gedit-replace.page
/usr/share/help/ca/gedit/gedit-save-file.page
/usr/share/help/ca/gedit/gedit-search.page
/usr/share/help/ca/gedit/gedit-shortcut-keys.page
/usr/share/help/ca/gedit/gedit-spellcheck.page
/usr/share/help/ca/gedit/gedit-syntax-highlighting.page
/usr/share/help/ca/gedit/gedit-tab-groups.page
/usr/share/help/ca/gedit/gedit-tabs-moving.page
/usr/share/help/ca/gedit/gedit-tabs.page
/usr/share/help/ca/gedit/gedit-undo-recent-action.page
/usr/share/help/ca/gedit/index.page
/usr/share/help/ca/gedit/legal.xml
/usr/share/help/cs/gedit/figures/gedit-html-snippet.png
/usr/share/help/cs/gedit/figures/gedit-icon.png
/usr/share/help/cs/gedit/figures/gedit3-screenshot.png
/usr/share/help/cs/gedit/gedit-change-color-scheme.page
/usr/share/help/cs/gedit/gedit-change-default-font.page
/usr/share/help/cs/gedit/gedit-close-file.page
/usr/share/help/cs/gedit/gedit-create-new-file.page
/usr/share/help/cs/gedit/gedit-edit-as-root.page
/usr/share/help/cs/gedit/gedit-files-basic.page
/usr/share/help/cs/gedit/gedit-full-screen.page
/usr/share/help/cs/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/cs/gedit/gedit-open-files.page
/usr/share/help/cs/gedit/gedit-open-on-server.page
/usr/share/help/cs/gedit/gedit-open-recent.page
/usr/share/help/cs/gedit/gedit-plugin-guide.page
/usr/share/help/cs/gedit/gedit-plugins-change-case.page
/usr/share/help/cs/gedit/gedit-plugins-doc-stats.page
/usr/share/help/cs/gedit/gedit-plugins-external-tools.page
/usr/share/help/cs/gedit/gedit-plugins-file-browser.page
/usr/share/help/cs/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/cs/gedit/gedit-plugins-install.page
/usr/share/help/cs/gedit/gedit-plugins-modelines.page
/usr/share/help/cs/gedit/gedit-plugins-pyconsole.page
/usr/share/help/cs/gedit/gedit-plugins-quick-open.page
/usr/share/help/cs/gedit/gedit-plugins-snippets.page
/usr/share/help/cs/gedit/gedit-plugins-sort.page
/usr/share/help/cs/gedit/gedit-printing-order.page
/usr/share/help/cs/gedit/gedit-printing-select.page
/usr/share/help/cs/gedit/gedit-printing.page
/usr/share/help/cs/gedit/gedit-quickstart.page
/usr/share/help/cs/gedit/gedit-replace.page
/usr/share/help/cs/gedit/gedit-save-file.page
/usr/share/help/cs/gedit/gedit-search.page
/usr/share/help/cs/gedit/gedit-shortcut-keys.page
/usr/share/help/cs/gedit/gedit-spellcheck.page
/usr/share/help/cs/gedit/gedit-syntax-highlighting.page
/usr/share/help/cs/gedit/gedit-tab-groups.page
/usr/share/help/cs/gedit/gedit-tabs-moving.page
/usr/share/help/cs/gedit/gedit-tabs.page
/usr/share/help/cs/gedit/gedit-undo-recent-action.page
/usr/share/help/cs/gedit/index.page
/usr/share/help/cs/gedit/legal.xml
/usr/share/help/da/gedit/figures/gedit-html-snippet.png
/usr/share/help/da/gedit/figures/gedit-icon.png
/usr/share/help/da/gedit/figures/gedit3-screenshot.png
/usr/share/help/da/gedit/gedit-change-color-scheme.page
/usr/share/help/da/gedit/gedit-change-default-font.page
/usr/share/help/da/gedit/gedit-close-file.page
/usr/share/help/da/gedit/gedit-create-new-file.page
/usr/share/help/da/gedit/gedit-edit-as-root.page
/usr/share/help/da/gedit/gedit-files-basic.page
/usr/share/help/da/gedit/gedit-full-screen.page
/usr/share/help/da/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/da/gedit/gedit-open-files.page
/usr/share/help/da/gedit/gedit-open-on-server.page
/usr/share/help/da/gedit/gedit-open-recent.page
/usr/share/help/da/gedit/gedit-plugin-guide.page
/usr/share/help/da/gedit/gedit-plugins-change-case.page
/usr/share/help/da/gedit/gedit-plugins-doc-stats.page
/usr/share/help/da/gedit/gedit-plugins-external-tools.page
/usr/share/help/da/gedit/gedit-plugins-file-browser.page
/usr/share/help/da/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/da/gedit/gedit-plugins-install.page
/usr/share/help/da/gedit/gedit-plugins-modelines.page
/usr/share/help/da/gedit/gedit-plugins-pyconsole.page
/usr/share/help/da/gedit/gedit-plugins-quick-open.page
/usr/share/help/da/gedit/gedit-plugins-snippets.page
/usr/share/help/da/gedit/gedit-plugins-sort.page
/usr/share/help/da/gedit/gedit-printing-order.page
/usr/share/help/da/gedit/gedit-printing-select.page
/usr/share/help/da/gedit/gedit-printing.page
/usr/share/help/da/gedit/gedit-quickstart.page
/usr/share/help/da/gedit/gedit-replace.page
/usr/share/help/da/gedit/gedit-save-file.page
/usr/share/help/da/gedit/gedit-search.page
/usr/share/help/da/gedit/gedit-shortcut-keys.page
/usr/share/help/da/gedit/gedit-spellcheck.page
/usr/share/help/da/gedit/gedit-syntax-highlighting.page
/usr/share/help/da/gedit/gedit-tab-groups.page
/usr/share/help/da/gedit/gedit-tabs-moving.page
/usr/share/help/da/gedit/gedit-tabs.page
/usr/share/help/da/gedit/gedit-undo-recent-action.page
/usr/share/help/da/gedit/index.page
/usr/share/help/da/gedit/legal.xml
/usr/share/help/de/gedit/figures/gedit-html-snippet.png
/usr/share/help/de/gedit/figures/gedit-icon.png
/usr/share/help/de/gedit/figures/gedit3-screenshot.png
/usr/share/help/de/gedit/gedit-change-color-scheme.page
/usr/share/help/de/gedit/gedit-change-default-font.page
/usr/share/help/de/gedit/gedit-close-file.page
/usr/share/help/de/gedit/gedit-create-new-file.page
/usr/share/help/de/gedit/gedit-edit-as-root.page
/usr/share/help/de/gedit/gedit-files-basic.page
/usr/share/help/de/gedit/gedit-full-screen.page
/usr/share/help/de/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/de/gedit/gedit-open-files.page
/usr/share/help/de/gedit/gedit-open-on-server.page
/usr/share/help/de/gedit/gedit-open-recent.page
/usr/share/help/de/gedit/gedit-plugin-guide.page
/usr/share/help/de/gedit/gedit-plugins-change-case.page
/usr/share/help/de/gedit/gedit-plugins-doc-stats.page
/usr/share/help/de/gedit/gedit-plugins-external-tools.page
/usr/share/help/de/gedit/gedit-plugins-file-browser.page
/usr/share/help/de/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/de/gedit/gedit-plugins-install.page
/usr/share/help/de/gedit/gedit-plugins-modelines.page
/usr/share/help/de/gedit/gedit-plugins-pyconsole.page
/usr/share/help/de/gedit/gedit-plugins-quick-open.page
/usr/share/help/de/gedit/gedit-plugins-snippets.page
/usr/share/help/de/gedit/gedit-plugins-sort.page
/usr/share/help/de/gedit/gedit-printing-order.page
/usr/share/help/de/gedit/gedit-printing-select.page
/usr/share/help/de/gedit/gedit-printing.page
/usr/share/help/de/gedit/gedit-quickstart.page
/usr/share/help/de/gedit/gedit-replace.page
/usr/share/help/de/gedit/gedit-save-file.page
/usr/share/help/de/gedit/gedit-search.page
/usr/share/help/de/gedit/gedit-shortcut-keys.page
/usr/share/help/de/gedit/gedit-spellcheck.page
/usr/share/help/de/gedit/gedit-syntax-highlighting.page
/usr/share/help/de/gedit/gedit-tab-groups.page
/usr/share/help/de/gedit/gedit-tabs-moving.page
/usr/share/help/de/gedit/gedit-tabs.page
/usr/share/help/de/gedit/gedit-undo-recent-action.page
/usr/share/help/de/gedit/index.page
/usr/share/help/de/gedit/legal.xml
/usr/share/help/el/gedit/figures/gedit-html-snippet.png
/usr/share/help/el/gedit/figures/gedit-icon.png
/usr/share/help/el/gedit/figures/gedit3-screenshot.png
/usr/share/help/el/gedit/gedit-change-color-scheme.page
/usr/share/help/el/gedit/gedit-change-default-font.page
/usr/share/help/el/gedit/gedit-close-file.page
/usr/share/help/el/gedit/gedit-create-new-file.page
/usr/share/help/el/gedit/gedit-edit-as-root.page
/usr/share/help/el/gedit/gedit-files-basic.page
/usr/share/help/el/gedit/gedit-full-screen.page
/usr/share/help/el/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/el/gedit/gedit-open-files.page
/usr/share/help/el/gedit/gedit-open-on-server.page
/usr/share/help/el/gedit/gedit-open-recent.page
/usr/share/help/el/gedit/gedit-plugin-guide.page
/usr/share/help/el/gedit/gedit-plugins-change-case.page
/usr/share/help/el/gedit/gedit-plugins-doc-stats.page
/usr/share/help/el/gedit/gedit-plugins-external-tools.page
/usr/share/help/el/gedit/gedit-plugins-file-browser.page
/usr/share/help/el/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/el/gedit/gedit-plugins-install.page
/usr/share/help/el/gedit/gedit-plugins-modelines.page
/usr/share/help/el/gedit/gedit-plugins-pyconsole.page
/usr/share/help/el/gedit/gedit-plugins-quick-open.page
/usr/share/help/el/gedit/gedit-plugins-snippets.page
/usr/share/help/el/gedit/gedit-plugins-sort.page
/usr/share/help/el/gedit/gedit-printing-order.page
/usr/share/help/el/gedit/gedit-printing-select.page
/usr/share/help/el/gedit/gedit-printing.page
/usr/share/help/el/gedit/gedit-quickstart.page
/usr/share/help/el/gedit/gedit-replace.page
/usr/share/help/el/gedit/gedit-save-file.page
/usr/share/help/el/gedit/gedit-search.page
/usr/share/help/el/gedit/gedit-shortcut-keys.page
/usr/share/help/el/gedit/gedit-spellcheck.page
/usr/share/help/el/gedit/gedit-syntax-highlighting.page
/usr/share/help/el/gedit/gedit-tab-groups.page
/usr/share/help/el/gedit/gedit-tabs-moving.page
/usr/share/help/el/gedit/gedit-tabs.page
/usr/share/help/el/gedit/gedit-undo-recent-action.page
/usr/share/help/el/gedit/index.page
/usr/share/help/el/gedit/legal.xml
/usr/share/help/es/gedit/figures/gedit-html-snippet.png
/usr/share/help/es/gedit/figures/gedit-icon.png
/usr/share/help/es/gedit/figures/gedit3-screenshot.png
/usr/share/help/es/gedit/gedit-change-color-scheme.page
/usr/share/help/es/gedit/gedit-change-default-font.page
/usr/share/help/es/gedit/gedit-close-file.page
/usr/share/help/es/gedit/gedit-create-new-file.page
/usr/share/help/es/gedit/gedit-edit-as-root.page
/usr/share/help/es/gedit/gedit-files-basic.page
/usr/share/help/es/gedit/gedit-full-screen.page
/usr/share/help/es/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/es/gedit/gedit-open-files.page
/usr/share/help/es/gedit/gedit-open-on-server.page
/usr/share/help/es/gedit/gedit-open-recent.page
/usr/share/help/es/gedit/gedit-plugin-guide.page
/usr/share/help/es/gedit/gedit-plugins-change-case.page
/usr/share/help/es/gedit/gedit-plugins-doc-stats.page
/usr/share/help/es/gedit/gedit-plugins-external-tools.page
/usr/share/help/es/gedit/gedit-plugins-file-browser.page
/usr/share/help/es/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/es/gedit/gedit-plugins-install.page
/usr/share/help/es/gedit/gedit-plugins-modelines.page
/usr/share/help/es/gedit/gedit-plugins-pyconsole.page
/usr/share/help/es/gedit/gedit-plugins-quick-open.page
/usr/share/help/es/gedit/gedit-plugins-snippets.page
/usr/share/help/es/gedit/gedit-plugins-sort.page
/usr/share/help/es/gedit/gedit-printing-order.page
/usr/share/help/es/gedit/gedit-printing-select.page
/usr/share/help/es/gedit/gedit-printing.page
/usr/share/help/es/gedit/gedit-quickstart.page
/usr/share/help/es/gedit/gedit-replace.page
/usr/share/help/es/gedit/gedit-save-file.page
/usr/share/help/es/gedit/gedit-search.page
/usr/share/help/es/gedit/gedit-shortcut-keys.page
/usr/share/help/es/gedit/gedit-spellcheck.page
/usr/share/help/es/gedit/gedit-syntax-highlighting.page
/usr/share/help/es/gedit/gedit-tab-groups.page
/usr/share/help/es/gedit/gedit-tabs-moving.page
/usr/share/help/es/gedit/gedit-tabs.page
/usr/share/help/es/gedit/gedit-undo-recent-action.page
/usr/share/help/es/gedit/index.page
/usr/share/help/es/gedit/legal.xml
/usr/share/help/eu/gedit/figures/gedit-html-snippet.png
/usr/share/help/eu/gedit/figures/gedit-icon.png
/usr/share/help/eu/gedit/figures/gedit3-screenshot.png
/usr/share/help/eu/gedit/gedit-change-color-scheme.page
/usr/share/help/eu/gedit/gedit-change-default-font.page
/usr/share/help/eu/gedit/gedit-close-file.page
/usr/share/help/eu/gedit/gedit-create-new-file.page
/usr/share/help/eu/gedit/gedit-edit-as-root.page
/usr/share/help/eu/gedit/gedit-files-basic.page
/usr/share/help/eu/gedit/gedit-full-screen.page
/usr/share/help/eu/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/eu/gedit/gedit-open-files.page
/usr/share/help/eu/gedit/gedit-open-on-server.page
/usr/share/help/eu/gedit/gedit-open-recent.page
/usr/share/help/eu/gedit/gedit-plugin-guide.page
/usr/share/help/eu/gedit/gedit-plugins-change-case.page
/usr/share/help/eu/gedit/gedit-plugins-doc-stats.page
/usr/share/help/eu/gedit/gedit-plugins-external-tools.page
/usr/share/help/eu/gedit/gedit-plugins-file-browser.page
/usr/share/help/eu/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/eu/gedit/gedit-plugins-install.page
/usr/share/help/eu/gedit/gedit-plugins-modelines.page
/usr/share/help/eu/gedit/gedit-plugins-pyconsole.page
/usr/share/help/eu/gedit/gedit-plugins-quick-open.page
/usr/share/help/eu/gedit/gedit-plugins-snippets.page
/usr/share/help/eu/gedit/gedit-plugins-sort.page
/usr/share/help/eu/gedit/gedit-printing-order.page
/usr/share/help/eu/gedit/gedit-printing-select.page
/usr/share/help/eu/gedit/gedit-printing.page
/usr/share/help/eu/gedit/gedit-quickstart.page
/usr/share/help/eu/gedit/gedit-replace.page
/usr/share/help/eu/gedit/gedit-save-file.page
/usr/share/help/eu/gedit/gedit-search.page
/usr/share/help/eu/gedit/gedit-shortcut-keys.page
/usr/share/help/eu/gedit/gedit-spellcheck.page
/usr/share/help/eu/gedit/gedit-syntax-highlighting.page
/usr/share/help/eu/gedit/gedit-tab-groups.page
/usr/share/help/eu/gedit/gedit-tabs-moving.page
/usr/share/help/eu/gedit/gedit-tabs.page
/usr/share/help/eu/gedit/gedit-undo-recent-action.page
/usr/share/help/eu/gedit/index.page
/usr/share/help/eu/gedit/legal.xml
/usr/share/help/fi/gedit/figures/gedit-html-snippet.png
/usr/share/help/fi/gedit/figures/gedit-icon.png
/usr/share/help/fi/gedit/figures/gedit3-screenshot.png
/usr/share/help/fi/gedit/gedit-change-color-scheme.page
/usr/share/help/fi/gedit/gedit-change-default-font.page
/usr/share/help/fi/gedit/gedit-close-file.page
/usr/share/help/fi/gedit/gedit-create-new-file.page
/usr/share/help/fi/gedit/gedit-edit-as-root.page
/usr/share/help/fi/gedit/gedit-files-basic.page
/usr/share/help/fi/gedit/gedit-full-screen.page
/usr/share/help/fi/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/fi/gedit/gedit-open-files.page
/usr/share/help/fi/gedit/gedit-open-on-server.page
/usr/share/help/fi/gedit/gedit-open-recent.page
/usr/share/help/fi/gedit/gedit-plugin-guide.page
/usr/share/help/fi/gedit/gedit-plugins-change-case.page
/usr/share/help/fi/gedit/gedit-plugins-doc-stats.page
/usr/share/help/fi/gedit/gedit-plugins-external-tools.page
/usr/share/help/fi/gedit/gedit-plugins-file-browser.page
/usr/share/help/fi/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/fi/gedit/gedit-plugins-install.page
/usr/share/help/fi/gedit/gedit-plugins-modelines.page
/usr/share/help/fi/gedit/gedit-plugins-pyconsole.page
/usr/share/help/fi/gedit/gedit-plugins-quick-open.page
/usr/share/help/fi/gedit/gedit-plugins-snippets.page
/usr/share/help/fi/gedit/gedit-plugins-sort.page
/usr/share/help/fi/gedit/gedit-printing-order.page
/usr/share/help/fi/gedit/gedit-printing-select.page
/usr/share/help/fi/gedit/gedit-printing.page
/usr/share/help/fi/gedit/gedit-quickstart.page
/usr/share/help/fi/gedit/gedit-replace.page
/usr/share/help/fi/gedit/gedit-save-file.page
/usr/share/help/fi/gedit/gedit-search.page
/usr/share/help/fi/gedit/gedit-shortcut-keys.page
/usr/share/help/fi/gedit/gedit-spellcheck.page
/usr/share/help/fi/gedit/gedit-syntax-highlighting.page
/usr/share/help/fi/gedit/gedit-tab-groups.page
/usr/share/help/fi/gedit/gedit-tabs-moving.page
/usr/share/help/fi/gedit/gedit-tabs.page
/usr/share/help/fi/gedit/gedit-undo-recent-action.page
/usr/share/help/fi/gedit/index.page
/usr/share/help/fi/gedit/legal.xml
/usr/share/help/fr/gedit/figures/gedit-html-snippet.png
/usr/share/help/fr/gedit/figures/gedit-icon.png
/usr/share/help/fr/gedit/figures/gedit3-screenshot.png
/usr/share/help/fr/gedit/gedit-change-color-scheme.page
/usr/share/help/fr/gedit/gedit-change-default-font.page
/usr/share/help/fr/gedit/gedit-close-file.page
/usr/share/help/fr/gedit/gedit-create-new-file.page
/usr/share/help/fr/gedit/gedit-edit-as-root.page
/usr/share/help/fr/gedit/gedit-files-basic.page
/usr/share/help/fr/gedit/gedit-full-screen.page
/usr/share/help/fr/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/fr/gedit/gedit-open-files.page
/usr/share/help/fr/gedit/gedit-open-on-server.page
/usr/share/help/fr/gedit/gedit-open-recent.page
/usr/share/help/fr/gedit/gedit-plugin-guide.page
/usr/share/help/fr/gedit/gedit-plugins-change-case.page
/usr/share/help/fr/gedit/gedit-plugins-doc-stats.page
/usr/share/help/fr/gedit/gedit-plugins-external-tools.page
/usr/share/help/fr/gedit/gedit-plugins-file-browser.page
/usr/share/help/fr/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/fr/gedit/gedit-plugins-install.page
/usr/share/help/fr/gedit/gedit-plugins-modelines.page
/usr/share/help/fr/gedit/gedit-plugins-pyconsole.page
/usr/share/help/fr/gedit/gedit-plugins-quick-open.page
/usr/share/help/fr/gedit/gedit-plugins-snippets.page
/usr/share/help/fr/gedit/gedit-plugins-sort.page
/usr/share/help/fr/gedit/gedit-printing-order.page
/usr/share/help/fr/gedit/gedit-printing-select.page
/usr/share/help/fr/gedit/gedit-printing.page
/usr/share/help/fr/gedit/gedit-quickstart.page
/usr/share/help/fr/gedit/gedit-replace.page
/usr/share/help/fr/gedit/gedit-save-file.page
/usr/share/help/fr/gedit/gedit-search.page
/usr/share/help/fr/gedit/gedit-shortcut-keys.page
/usr/share/help/fr/gedit/gedit-spellcheck.page
/usr/share/help/fr/gedit/gedit-syntax-highlighting.page
/usr/share/help/fr/gedit/gedit-tab-groups.page
/usr/share/help/fr/gedit/gedit-tabs-moving.page
/usr/share/help/fr/gedit/gedit-tabs.page
/usr/share/help/fr/gedit/gedit-undo-recent-action.page
/usr/share/help/fr/gedit/index.page
/usr/share/help/fr/gedit/legal.xml
/usr/share/help/gl/gedit/figures/gedit-html-snippet.png
/usr/share/help/gl/gedit/figures/gedit-icon.png
/usr/share/help/gl/gedit/figures/gedit3-screenshot.png
/usr/share/help/gl/gedit/gedit-change-color-scheme.page
/usr/share/help/gl/gedit/gedit-change-default-font.page
/usr/share/help/gl/gedit/gedit-close-file.page
/usr/share/help/gl/gedit/gedit-create-new-file.page
/usr/share/help/gl/gedit/gedit-edit-as-root.page
/usr/share/help/gl/gedit/gedit-files-basic.page
/usr/share/help/gl/gedit/gedit-full-screen.page
/usr/share/help/gl/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/gl/gedit/gedit-open-files.page
/usr/share/help/gl/gedit/gedit-open-on-server.page
/usr/share/help/gl/gedit/gedit-open-recent.page
/usr/share/help/gl/gedit/gedit-plugin-guide.page
/usr/share/help/gl/gedit/gedit-plugins-change-case.page
/usr/share/help/gl/gedit/gedit-plugins-doc-stats.page
/usr/share/help/gl/gedit/gedit-plugins-external-tools.page
/usr/share/help/gl/gedit/gedit-plugins-file-browser.page
/usr/share/help/gl/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/gl/gedit/gedit-plugins-install.page
/usr/share/help/gl/gedit/gedit-plugins-modelines.page
/usr/share/help/gl/gedit/gedit-plugins-pyconsole.page
/usr/share/help/gl/gedit/gedit-plugins-quick-open.page
/usr/share/help/gl/gedit/gedit-plugins-snippets.page
/usr/share/help/gl/gedit/gedit-plugins-sort.page
/usr/share/help/gl/gedit/gedit-printing-order.page
/usr/share/help/gl/gedit/gedit-printing-select.page
/usr/share/help/gl/gedit/gedit-printing.page
/usr/share/help/gl/gedit/gedit-quickstart.page
/usr/share/help/gl/gedit/gedit-replace.page
/usr/share/help/gl/gedit/gedit-save-file.page
/usr/share/help/gl/gedit/gedit-search.page
/usr/share/help/gl/gedit/gedit-shortcut-keys.page
/usr/share/help/gl/gedit/gedit-spellcheck.page
/usr/share/help/gl/gedit/gedit-syntax-highlighting.page
/usr/share/help/gl/gedit/gedit-tab-groups.page
/usr/share/help/gl/gedit/gedit-tabs-moving.page
/usr/share/help/gl/gedit/gedit-tabs.page
/usr/share/help/gl/gedit/gedit-undo-recent-action.page
/usr/share/help/gl/gedit/index.page
/usr/share/help/gl/gedit/legal.xml
/usr/share/help/hu/gedit/figures/gedit-html-snippet.png
/usr/share/help/hu/gedit/figures/gedit-icon.png
/usr/share/help/hu/gedit/figures/gedit3-screenshot.png
/usr/share/help/hu/gedit/gedit-change-color-scheme.page
/usr/share/help/hu/gedit/gedit-change-default-font.page
/usr/share/help/hu/gedit/gedit-close-file.page
/usr/share/help/hu/gedit/gedit-create-new-file.page
/usr/share/help/hu/gedit/gedit-edit-as-root.page
/usr/share/help/hu/gedit/gedit-files-basic.page
/usr/share/help/hu/gedit/gedit-full-screen.page
/usr/share/help/hu/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/hu/gedit/gedit-open-files.page
/usr/share/help/hu/gedit/gedit-open-on-server.page
/usr/share/help/hu/gedit/gedit-open-recent.page
/usr/share/help/hu/gedit/gedit-plugin-guide.page
/usr/share/help/hu/gedit/gedit-plugins-change-case.page
/usr/share/help/hu/gedit/gedit-plugins-doc-stats.page
/usr/share/help/hu/gedit/gedit-plugins-external-tools.page
/usr/share/help/hu/gedit/gedit-plugins-file-browser.page
/usr/share/help/hu/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/hu/gedit/gedit-plugins-install.page
/usr/share/help/hu/gedit/gedit-plugins-modelines.page
/usr/share/help/hu/gedit/gedit-plugins-pyconsole.page
/usr/share/help/hu/gedit/gedit-plugins-quick-open.page
/usr/share/help/hu/gedit/gedit-plugins-snippets.page
/usr/share/help/hu/gedit/gedit-plugins-sort.page
/usr/share/help/hu/gedit/gedit-printing-order.page
/usr/share/help/hu/gedit/gedit-printing-select.page
/usr/share/help/hu/gedit/gedit-printing.page
/usr/share/help/hu/gedit/gedit-quickstart.page
/usr/share/help/hu/gedit/gedit-replace.page
/usr/share/help/hu/gedit/gedit-save-file.page
/usr/share/help/hu/gedit/gedit-search.page
/usr/share/help/hu/gedit/gedit-shortcut-keys.page
/usr/share/help/hu/gedit/gedit-spellcheck.page
/usr/share/help/hu/gedit/gedit-syntax-highlighting.page
/usr/share/help/hu/gedit/gedit-tab-groups.page
/usr/share/help/hu/gedit/gedit-tabs-moving.page
/usr/share/help/hu/gedit/gedit-tabs.page
/usr/share/help/hu/gedit/gedit-undo-recent-action.page
/usr/share/help/hu/gedit/index.page
/usr/share/help/hu/gedit/legal.xml
/usr/share/help/id/gedit/figures/gedit-html-snippet.png
/usr/share/help/id/gedit/figures/gedit-icon.png
/usr/share/help/id/gedit/figures/gedit3-screenshot.png
/usr/share/help/id/gedit/gedit-change-color-scheme.page
/usr/share/help/id/gedit/gedit-change-default-font.page
/usr/share/help/id/gedit/gedit-close-file.page
/usr/share/help/id/gedit/gedit-create-new-file.page
/usr/share/help/id/gedit/gedit-edit-as-root.page
/usr/share/help/id/gedit/gedit-files-basic.page
/usr/share/help/id/gedit/gedit-full-screen.page
/usr/share/help/id/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/id/gedit/gedit-open-files.page
/usr/share/help/id/gedit/gedit-open-on-server.page
/usr/share/help/id/gedit/gedit-open-recent.page
/usr/share/help/id/gedit/gedit-plugin-guide.page
/usr/share/help/id/gedit/gedit-plugins-change-case.page
/usr/share/help/id/gedit/gedit-plugins-doc-stats.page
/usr/share/help/id/gedit/gedit-plugins-external-tools.page
/usr/share/help/id/gedit/gedit-plugins-file-browser.page
/usr/share/help/id/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/id/gedit/gedit-plugins-install.page
/usr/share/help/id/gedit/gedit-plugins-modelines.page
/usr/share/help/id/gedit/gedit-plugins-pyconsole.page
/usr/share/help/id/gedit/gedit-plugins-quick-open.page
/usr/share/help/id/gedit/gedit-plugins-snippets.page
/usr/share/help/id/gedit/gedit-plugins-sort.page
/usr/share/help/id/gedit/gedit-printing-order.page
/usr/share/help/id/gedit/gedit-printing-select.page
/usr/share/help/id/gedit/gedit-printing.page
/usr/share/help/id/gedit/gedit-quickstart.page
/usr/share/help/id/gedit/gedit-replace.page
/usr/share/help/id/gedit/gedit-save-file.page
/usr/share/help/id/gedit/gedit-search.page
/usr/share/help/id/gedit/gedit-shortcut-keys.page
/usr/share/help/id/gedit/gedit-spellcheck.page
/usr/share/help/id/gedit/gedit-syntax-highlighting.page
/usr/share/help/id/gedit/gedit-tab-groups.page
/usr/share/help/id/gedit/gedit-tabs-moving.page
/usr/share/help/id/gedit/gedit-tabs.page
/usr/share/help/id/gedit/gedit-undo-recent-action.page
/usr/share/help/id/gedit/index.page
/usr/share/help/id/gedit/legal.xml
/usr/share/help/it/gedit/figures/gedit-html-snippet.png
/usr/share/help/it/gedit/figures/gedit-icon.png
/usr/share/help/it/gedit/figures/gedit3-screenshot.png
/usr/share/help/it/gedit/gedit-change-color-scheme.page
/usr/share/help/it/gedit/gedit-change-default-font.page
/usr/share/help/it/gedit/gedit-close-file.page
/usr/share/help/it/gedit/gedit-create-new-file.page
/usr/share/help/it/gedit/gedit-edit-as-root.page
/usr/share/help/it/gedit/gedit-files-basic.page
/usr/share/help/it/gedit/gedit-full-screen.page
/usr/share/help/it/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/it/gedit/gedit-open-files.page
/usr/share/help/it/gedit/gedit-open-on-server.page
/usr/share/help/it/gedit/gedit-open-recent.page
/usr/share/help/it/gedit/gedit-plugin-guide.page
/usr/share/help/it/gedit/gedit-plugins-change-case.page
/usr/share/help/it/gedit/gedit-plugins-doc-stats.page
/usr/share/help/it/gedit/gedit-plugins-external-tools.page
/usr/share/help/it/gedit/gedit-plugins-file-browser.page
/usr/share/help/it/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/it/gedit/gedit-plugins-install.page
/usr/share/help/it/gedit/gedit-plugins-modelines.page
/usr/share/help/it/gedit/gedit-plugins-pyconsole.page
/usr/share/help/it/gedit/gedit-plugins-quick-open.page
/usr/share/help/it/gedit/gedit-plugins-snippets.page
/usr/share/help/it/gedit/gedit-plugins-sort.page
/usr/share/help/it/gedit/gedit-printing-order.page
/usr/share/help/it/gedit/gedit-printing-select.page
/usr/share/help/it/gedit/gedit-printing.page
/usr/share/help/it/gedit/gedit-quickstart.page
/usr/share/help/it/gedit/gedit-replace.page
/usr/share/help/it/gedit/gedit-save-file.page
/usr/share/help/it/gedit/gedit-search.page
/usr/share/help/it/gedit/gedit-shortcut-keys.page
/usr/share/help/it/gedit/gedit-spellcheck.page
/usr/share/help/it/gedit/gedit-syntax-highlighting.page
/usr/share/help/it/gedit/gedit-tab-groups.page
/usr/share/help/it/gedit/gedit-tabs-moving.page
/usr/share/help/it/gedit/gedit-tabs.page
/usr/share/help/it/gedit/gedit-undo-recent-action.page
/usr/share/help/it/gedit/index.page
/usr/share/help/it/gedit/legal.xml
/usr/share/help/ja/gedit/figures/gedit-html-snippet.png
/usr/share/help/ja/gedit/figures/gedit-icon.png
/usr/share/help/ja/gedit/figures/gedit3-screenshot.png
/usr/share/help/ja/gedit/gedit-change-color-scheme.page
/usr/share/help/ja/gedit/gedit-change-default-font.page
/usr/share/help/ja/gedit/gedit-close-file.page
/usr/share/help/ja/gedit/gedit-create-new-file.page
/usr/share/help/ja/gedit/gedit-edit-as-root.page
/usr/share/help/ja/gedit/gedit-files-basic.page
/usr/share/help/ja/gedit/gedit-full-screen.page
/usr/share/help/ja/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/ja/gedit/gedit-open-files.page
/usr/share/help/ja/gedit/gedit-open-on-server.page
/usr/share/help/ja/gedit/gedit-open-recent.page
/usr/share/help/ja/gedit/gedit-plugin-guide.page
/usr/share/help/ja/gedit/gedit-plugins-change-case.page
/usr/share/help/ja/gedit/gedit-plugins-doc-stats.page
/usr/share/help/ja/gedit/gedit-plugins-external-tools.page
/usr/share/help/ja/gedit/gedit-plugins-file-browser.page
/usr/share/help/ja/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/ja/gedit/gedit-plugins-install.page
/usr/share/help/ja/gedit/gedit-plugins-modelines.page
/usr/share/help/ja/gedit/gedit-plugins-pyconsole.page
/usr/share/help/ja/gedit/gedit-plugins-quick-open.page
/usr/share/help/ja/gedit/gedit-plugins-snippets.page
/usr/share/help/ja/gedit/gedit-plugins-sort.page
/usr/share/help/ja/gedit/gedit-printing-order.page
/usr/share/help/ja/gedit/gedit-printing-select.page
/usr/share/help/ja/gedit/gedit-printing.page
/usr/share/help/ja/gedit/gedit-quickstart.page
/usr/share/help/ja/gedit/gedit-replace.page
/usr/share/help/ja/gedit/gedit-save-file.page
/usr/share/help/ja/gedit/gedit-search.page
/usr/share/help/ja/gedit/gedit-shortcut-keys.page
/usr/share/help/ja/gedit/gedit-spellcheck.page
/usr/share/help/ja/gedit/gedit-syntax-highlighting.page
/usr/share/help/ja/gedit/gedit-tab-groups.page
/usr/share/help/ja/gedit/gedit-tabs-moving.page
/usr/share/help/ja/gedit/gedit-tabs.page
/usr/share/help/ja/gedit/gedit-undo-recent-action.page
/usr/share/help/ja/gedit/index.page
/usr/share/help/ja/gedit/legal.xml
/usr/share/help/ko/gedit/figures/gedit-html-snippet.png
/usr/share/help/ko/gedit/figures/gedit-icon.png
/usr/share/help/ko/gedit/figures/gedit3-screenshot.png
/usr/share/help/ko/gedit/gedit-change-color-scheme.page
/usr/share/help/ko/gedit/gedit-change-default-font.page
/usr/share/help/ko/gedit/gedit-close-file.page
/usr/share/help/ko/gedit/gedit-create-new-file.page
/usr/share/help/ko/gedit/gedit-edit-as-root.page
/usr/share/help/ko/gedit/gedit-files-basic.page
/usr/share/help/ko/gedit/gedit-full-screen.page
/usr/share/help/ko/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/ko/gedit/gedit-open-files.page
/usr/share/help/ko/gedit/gedit-open-on-server.page
/usr/share/help/ko/gedit/gedit-open-recent.page
/usr/share/help/ko/gedit/gedit-plugin-guide.page
/usr/share/help/ko/gedit/gedit-plugins-change-case.page
/usr/share/help/ko/gedit/gedit-plugins-doc-stats.page
/usr/share/help/ko/gedit/gedit-plugins-external-tools.page
/usr/share/help/ko/gedit/gedit-plugins-file-browser.page
/usr/share/help/ko/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/ko/gedit/gedit-plugins-install.page
/usr/share/help/ko/gedit/gedit-plugins-modelines.page
/usr/share/help/ko/gedit/gedit-plugins-pyconsole.page
/usr/share/help/ko/gedit/gedit-plugins-quick-open.page
/usr/share/help/ko/gedit/gedit-plugins-snippets.page
/usr/share/help/ko/gedit/gedit-plugins-sort.page
/usr/share/help/ko/gedit/gedit-printing-order.page
/usr/share/help/ko/gedit/gedit-printing-select.page
/usr/share/help/ko/gedit/gedit-printing.page
/usr/share/help/ko/gedit/gedit-quickstart.page
/usr/share/help/ko/gedit/gedit-replace.page
/usr/share/help/ko/gedit/gedit-save-file.page
/usr/share/help/ko/gedit/gedit-search.page
/usr/share/help/ko/gedit/gedit-shortcut-keys.page
/usr/share/help/ko/gedit/gedit-spellcheck.page
/usr/share/help/ko/gedit/gedit-syntax-highlighting.page
/usr/share/help/ko/gedit/gedit-tab-groups.page
/usr/share/help/ko/gedit/gedit-tabs-moving.page
/usr/share/help/ko/gedit/gedit-tabs.page
/usr/share/help/ko/gedit/gedit-undo-recent-action.page
/usr/share/help/ko/gedit/index.page
/usr/share/help/ko/gedit/legal.xml
/usr/share/help/lv/gedit/figures/gedit-html-snippet.png
/usr/share/help/lv/gedit/figures/gedit-icon.png
/usr/share/help/lv/gedit/figures/gedit3-screenshot.png
/usr/share/help/lv/gedit/gedit-change-color-scheme.page
/usr/share/help/lv/gedit/gedit-change-default-font.page
/usr/share/help/lv/gedit/gedit-close-file.page
/usr/share/help/lv/gedit/gedit-create-new-file.page
/usr/share/help/lv/gedit/gedit-edit-as-root.page
/usr/share/help/lv/gedit/gedit-files-basic.page
/usr/share/help/lv/gedit/gedit-full-screen.page
/usr/share/help/lv/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/lv/gedit/gedit-open-files.page
/usr/share/help/lv/gedit/gedit-open-on-server.page
/usr/share/help/lv/gedit/gedit-open-recent.page
/usr/share/help/lv/gedit/gedit-plugin-guide.page
/usr/share/help/lv/gedit/gedit-plugins-change-case.page
/usr/share/help/lv/gedit/gedit-plugins-doc-stats.page
/usr/share/help/lv/gedit/gedit-plugins-external-tools.page
/usr/share/help/lv/gedit/gedit-plugins-file-browser.page
/usr/share/help/lv/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/lv/gedit/gedit-plugins-install.page
/usr/share/help/lv/gedit/gedit-plugins-modelines.page
/usr/share/help/lv/gedit/gedit-plugins-pyconsole.page
/usr/share/help/lv/gedit/gedit-plugins-quick-open.page
/usr/share/help/lv/gedit/gedit-plugins-snippets.page
/usr/share/help/lv/gedit/gedit-plugins-sort.page
/usr/share/help/lv/gedit/gedit-printing-order.page
/usr/share/help/lv/gedit/gedit-printing-select.page
/usr/share/help/lv/gedit/gedit-printing.page
/usr/share/help/lv/gedit/gedit-quickstart.page
/usr/share/help/lv/gedit/gedit-replace.page
/usr/share/help/lv/gedit/gedit-save-file.page
/usr/share/help/lv/gedit/gedit-search.page
/usr/share/help/lv/gedit/gedit-shortcut-keys.page
/usr/share/help/lv/gedit/gedit-spellcheck.page
/usr/share/help/lv/gedit/gedit-syntax-highlighting.page
/usr/share/help/lv/gedit/gedit-tab-groups.page
/usr/share/help/lv/gedit/gedit-tabs-moving.page
/usr/share/help/lv/gedit/gedit-tabs.page
/usr/share/help/lv/gedit/gedit-undo-recent-action.page
/usr/share/help/lv/gedit/index.page
/usr/share/help/lv/gedit/legal.xml
/usr/share/help/oc/gedit/figures/gedit-html-snippet.png
/usr/share/help/oc/gedit/figures/gedit-icon.png
/usr/share/help/oc/gedit/figures/gedit3-screenshot.png
/usr/share/help/oc/gedit/gedit-change-color-scheme.page
/usr/share/help/oc/gedit/gedit-change-default-font.page
/usr/share/help/oc/gedit/gedit-close-file.page
/usr/share/help/oc/gedit/gedit-create-new-file.page
/usr/share/help/oc/gedit/gedit-edit-as-root.page
/usr/share/help/oc/gedit/gedit-files-basic.page
/usr/share/help/oc/gedit/gedit-full-screen.page
/usr/share/help/oc/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/oc/gedit/gedit-open-files.page
/usr/share/help/oc/gedit/gedit-open-on-server.page
/usr/share/help/oc/gedit/gedit-open-recent.page
/usr/share/help/oc/gedit/gedit-plugin-guide.page
/usr/share/help/oc/gedit/gedit-plugins-change-case.page
/usr/share/help/oc/gedit/gedit-plugins-doc-stats.page
/usr/share/help/oc/gedit/gedit-plugins-external-tools.page
/usr/share/help/oc/gedit/gedit-plugins-file-browser.page
/usr/share/help/oc/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/oc/gedit/gedit-plugins-install.page
/usr/share/help/oc/gedit/gedit-plugins-modelines.page
/usr/share/help/oc/gedit/gedit-plugins-pyconsole.page
/usr/share/help/oc/gedit/gedit-plugins-quick-open.page
/usr/share/help/oc/gedit/gedit-plugins-snippets.page
/usr/share/help/oc/gedit/gedit-plugins-sort.page
/usr/share/help/oc/gedit/gedit-printing-order.page
/usr/share/help/oc/gedit/gedit-printing-select.page
/usr/share/help/oc/gedit/gedit-printing.page
/usr/share/help/oc/gedit/gedit-quickstart.page
/usr/share/help/oc/gedit/gedit-replace.page
/usr/share/help/oc/gedit/gedit-save-file.page
/usr/share/help/oc/gedit/gedit-search.page
/usr/share/help/oc/gedit/gedit-shortcut-keys.page
/usr/share/help/oc/gedit/gedit-spellcheck.page
/usr/share/help/oc/gedit/gedit-syntax-highlighting.page
/usr/share/help/oc/gedit/gedit-tab-groups.page
/usr/share/help/oc/gedit/gedit-tabs-moving.page
/usr/share/help/oc/gedit/gedit-tabs.page
/usr/share/help/oc/gedit/gedit-undo-recent-action.page
/usr/share/help/oc/gedit/index.page
/usr/share/help/oc/gedit/legal.xml
/usr/share/help/pl/gedit/figures/gedit-html-snippet.png
/usr/share/help/pl/gedit/figures/gedit-icon.png
/usr/share/help/pl/gedit/figures/gedit3-screenshot.png
/usr/share/help/pl/gedit/gedit-change-color-scheme.page
/usr/share/help/pl/gedit/gedit-change-default-font.page
/usr/share/help/pl/gedit/gedit-close-file.page
/usr/share/help/pl/gedit/gedit-create-new-file.page
/usr/share/help/pl/gedit/gedit-edit-as-root.page
/usr/share/help/pl/gedit/gedit-files-basic.page
/usr/share/help/pl/gedit/gedit-full-screen.page
/usr/share/help/pl/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/pl/gedit/gedit-open-files.page
/usr/share/help/pl/gedit/gedit-open-on-server.page
/usr/share/help/pl/gedit/gedit-open-recent.page
/usr/share/help/pl/gedit/gedit-plugin-guide.page
/usr/share/help/pl/gedit/gedit-plugins-change-case.page
/usr/share/help/pl/gedit/gedit-plugins-doc-stats.page
/usr/share/help/pl/gedit/gedit-plugins-external-tools.page
/usr/share/help/pl/gedit/gedit-plugins-file-browser.page
/usr/share/help/pl/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/pl/gedit/gedit-plugins-install.page
/usr/share/help/pl/gedit/gedit-plugins-modelines.page
/usr/share/help/pl/gedit/gedit-plugins-pyconsole.page
/usr/share/help/pl/gedit/gedit-plugins-quick-open.page
/usr/share/help/pl/gedit/gedit-plugins-snippets.page
/usr/share/help/pl/gedit/gedit-plugins-sort.page
/usr/share/help/pl/gedit/gedit-printing-order.page
/usr/share/help/pl/gedit/gedit-printing-select.page
/usr/share/help/pl/gedit/gedit-printing.page
/usr/share/help/pl/gedit/gedit-quickstart.page
/usr/share/help/pl/gedit/gedit-replace.page
/usr/share/help/pl/gedit/gedit-save-file.page
/usr/share/help/pl/gedit/gedit-search.page
/usr/share/help/pl/gedit/gedit-shortcut-keys.page
/usr/share/help/pl/gedit/gedit-spellcheck.page
/usr/share/help/pl/gedit/gedit-syntax-highlighting.page
/usr/share/help/pl/gedit/gedit-tab-groups.page
/usr/share/help/pl/gedit/gedit-tabs-moving.page
/usr/share/help/pl/gedit/gedit-tabs.page
/usr/share/help/pl/gedit/gedit-undo-recent-action.page
/usr/share/help/pl/gedit/index.page
/usr/share/help/pl/gedit/legal.xml
/usr/share/help/pt_BR/gedit/figures/gedit-html-snippet.png
/usr/share/help/pt_BR/gedit/figures/gedit-icon.png
/usr/share/help/pt_BR/gedit/figures/gedit3-screenshot.png
/usr/share/help/pt_BR/gedit/gedit-change-color-scheme.page
/usr/share/help/pt_BR/gedit/gedit-change-default-font.page
/usr/share/help/pt_BR/gedit/gedit-close-file.page
/usr/share/help/pt_BR/gedit/gedit-create-new-file.page
/usr/share/help/pt_BR/gedit/gedit-edit-as-root.page
/usr/share/help/pt_BR/gedit/gedit-files-basic.page
/usr/share/help/pt_BR/gedit/gedit-full-screen.page
/usr/share/help/pt_BR/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/pt_BR/gedit/gedit-open-files.page
/usr/share/help/pt_BR/gedit/gedit-open-on-server.page
/usr/share/help/pt_BR/gedit/gedit-open-recent.page
/usr/share/help/pt_BR/gedit/gedit-plugin-guide.page
/usr/share/help/pt_BR/gedit/gedit-plugins-change-case.page
/usr/share/help/pt_BR/gedit/gedit-plugins-doc-stats.page
/usr/share/help/pt_BR/gedit/gedit-plugins-external-tools.page
/usr/share/help/pt_BR/gedit/gedit-plugins-file-browser.page
/usr/share/help/pt_BR/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/pt_BR/gedit/gedit-plugins-install.page
/usr/share/help/pt_BR/gedit/gedit-plugins-modelines.page
/usr/share/help/pt_BR/gedit/gedit-plugins-pyconsole.page
/usr/share/help/pt_BR/gedit/gedit-plugins-quick-open.page
/usr/share/help/pt_BR/gedit/gedit-plugins-snippets.page
/usr/share/help/pt_BR/gedit/gedit-plugins-sort.page
/usr/share/help/pt_BR/gedit/gedit-printing-order.page
/usr/share/help/pt_BR/gedit/gedit-printing-select.page
/usr/share/help/pt_BR/gedit/gedit-printing.page
/usr/share/help/pt_BR/gedit/gedit-quickstart.page
/usr/share/help/pt_BR/gedit/gedit-replace.page
/usr/share/help/pt_BR/gedit/gedit-save-file.page
/usr/share/help/pt_BR/gedit/gedit-search.page
/usr/share/help/pt_BR/gedit/gedit-shortcut-keys.page
/usr/share/help/pt_BR/gedit/gedit-spellcheck.page
/usr/share/help/pt_BR/gedit/gedit-syntax-highlighting.page
/usr/share/help/pt_BR/gedit/gedit-tab-groups.page
/usr/share/help/pt_BR/gedit/gedit-tabs-moving.page
/usr/share/help/pt_BR/gedit/gedit-tabs.page
/usr/share/help/pt_BR/gedit/gedit-undo-recent-action.page
/usr/share/help/pt_BR/gedit/index.page
/usr/share/help/pt_BR/gedit/legal.xml
/usr/share/help/ro/gedit/figures/gedit-html-snippet.png
/usr/share/help/ro/gedit/figures/gedit-icon.png
/usr/share/help/ro/gedit/figures/gedit3-screenshot.png
/usr/share/help/ro/gedit/gedit-change-color-scheme.page
/usr/share/help/ro/gedit/gedit-change-default-font.page
/usr/share/help/ro/gedit/gedit-close-file.page
/usr/share/help/ro/gedit/gedit-create-new-file.page
/usr/share/help/ro/gedit/gedit-edit-as-root.page
/usr/share/help/ro/gedit/gedit-files-basic.page
/usr/share/help/ro/gedit/gedit-full-screen.page
/usr/share/help/ro/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/ro/gedit/gedit-open-files.page
/usr/share/help/ro/gedit/gedit-open-on-server.page
/usr/share/help/ro/gedit/gedit-open-recent.page
/usr/share/help/ro/gedit/gedit-plugin-guide.page
/usr/share/help/ro/gedit/gedit-plugins-change-case.page
/usr/share/help/ro/gedit/gedit-plugins-doc-stats.page
/usr/share/help/ro/gedit/gedit-plugins-external-tools.page
/usr/share/help/ro/gedit/gedit-plugins-file-browser.page
/usr/share/help/ro/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/ro/gedit/gedit-plugins-install.page
/usr/share/help/ro/gedit/gedit-plugins-modelines.page
/usr/share/help/ro/gedit/gedit-plugins-pyconsole.page
/usr/share/help/ro/gedit/gedit-plugins-quick-open.page
/usr/share/help/ro/gedit/gedit-plugins-snippets.page
/usr/share/help/ro/gedit/gedit-plugins-sort.page
/usr/share/help/ro/gedit/gedit-printing-order.page
/usr/share/help/ro/gedit/gedit-printing-select.page
/usr/share/help/ro/gedit/gedit-printing.page
/usr/share/help/ro/gedit/gedit-quickstart.page
/usr/share/help/ro/gedit/gedit-replace.page
/usr/share/help/ro/gedit/gedit-save-file.page
/usr/share/help/ro/gedit/gedit-search.page
/usr/share/help/ro/gedit/gedit-shortcut-keys.page
/usr/share/help/ro/gedit/gedit-spellcheck.page
/usr/share/help/ro/gedit/gedit-syntax-highlighting.page
/usr/share/help/ro/gedit/gedit-tab-groups.page
/usr/share/help/ro/gedit/gedit-tabs-moving.page
/usr/share/help/ro/gedit/gedit-tabs.page
/usr/share/help/ro/gedit/gedit-undo-recent-action.page
/usr/share/help/ro/gedit/index.page
/usr/share/help/ro/gedit/legal.xml
/usr/share/help/ru/gedit/figures/gedit-html-snippet.png
/usr/share/help/ru/gedit/figures/gedit-icon.png
/usr/share/help/ru/gedit/figures/gedit3-screenshot.png
/usr/share/help/ru/gedit/gedit-change-color-scheme.page
/usr/share/help/ru/gedit/gedit-change-default-font.page
/usr/share/help/ru/gedit/gedit-close-file.page
/usr/share/help/ru/gedit/gedit-create-new-file.page
/usr/share/help/ru/gedit/gedit-edit-as-root.page
/usr/share/help/ru/gedit/gedit-files-basic.page
/usr/share/help/ru/gedit/gedit-full-screen.page
/usr/share/help/ru/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/ru/gedit/gedit-open-files.page
/usr/share/help/ru/gedit/gedit-open-on-server.page
/usr/share/help/ru/gedit/gedit-open-recent.page
/usr/share/help/ru/gedit/gedit-plugin-guide.page
/usr/share/help/ru/gedit/gedit-plugins-change-case.page
/usr/share/help/ru/gedit/gedit-plugins-doc-stats.page
/usr/share/help/ru/gedit/gedit-plugins-external-tools.page
/usr/share/help/ru/gedit/gedit-plugins-file-browser.page
/usr/share/help/ru/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/ru/gedit/gedit-plugins-install.page
/usr/share/help/ru/gedit/gedit-plugins-modelines.page
/usr/share/help/ru/gedit/gedit-plugins-pyconsole.page
/usr/share/help/ru/gedit/gedit-plugins-quick-open.page
/usr/share/help/ru/gedit/gedit-plugins-snippets.page
/usr/share/help/ru/gedit/gedit-plugins-sort.page
/usr/share/help/ru/gedit/gedit-printing-order.page
/usr/share/help/ru/gedit/gedit-printing-select.page
/usr/share/help/ru/gedit/gedit-printing.page
/usr/share/help/ru/gedit/gedit-quickstart.page
/usr/share/help/ru/gedit/gedit-replace.page
/usr/share/help/ru/gedit/gedit-save-file.page
/usr/share/help/ru/gedit/gedit-search.page
/usr/share/help/ru/gedit/gedit-shortcut-keys.page
/usr/share/help/ru/gedit/gedit-spellcheck.page
/usr/share/help/ru/gedit/gedit-syntax-highlighting.page
/usr/share/help/ru/gedit/gedit-tab-groups.page
/usr/share/help/ru/gedit/gedit-tabs-moving.page
/usr/share/help/ru/gedit/gedit-tabs.page
/usr/share/help/ru/gedit/gedit-undo-recent-action.page
/usr/share/help/ru/gedit/index.page
/usr/share/help/ru/gedit/legal.xml
/usr/share/help/sl/gedit/figures/gedit-html-snippet.png
/usr/share/help/sl/gedit/figures/gedit-icon.png
/usr/share/help/sl/gedit/figures/gedit3-screenshot.png
/usr/share/help/sl/gedit/gedit-change-color-scheme.page
/usr/share/help/sl/gedit/gedit-change-default-font.page
/usr/share/help/sl/gedit/gedit-close-file.page
/usr/share/help/sl/gedit/gedit-create-new-file.page
/usr/share/help/sl/gedit/gedit-edit-as-root.page
/usr/share/help/sl/gedit/gedit-files-basic.page
/usr/share/help/sl/gedit/gedit-full-screen.page
/usr/share/help/sl/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/sl/gedit/gedit-open-files.page
/usr/share/help/sl/gedit/gedit-open-on-server.page
/usr/share/help/sl/gedit/gedit-open-recent.page
/usr/share/help/sl/gedit/gedit-plugin-guide.page
/usr/share/help/sl/gedit/gedit-plugins-change-case.page
/usr/share/help/sl/gedit/gedit-plugins-doc-stats.page
/usr/share/help/sl/gedit/gedit-plugins-external-tools.page
/usr/share/help/sl/gedit/gedit-plugins-file-browser.page
/usr/share/help/sl/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/sl/gedit/gedit-plugins-install.page
/usr/share/help/sl/gedit/gedit-plugins-modelines.page
/usr/share/help/sl/gedit/gedit-plugins-pyconsole.page
/usr/share/help/sl/gedit/gedit-plugins-quick-open.page
/usr/share/help/sl/gedit/gedit-plugins-snippets.page
/usr/share/help/sl/gedit/gedit-plugins-sort.page
/usr/share/help/sl/gedit/gedit-printing-order.page
/usr/share/help/sl/gedit/gedit-printing-select.page
/usr/share/help/sl/gedit/gedit-printing.page
/usr/share/help/sl/gedit/gedit-quickstart.page
/usr/share/help/sl/gedit/gedit-replace.page
/usr/share/help/sl/gedit/gedit-save-file.page
/usr/share/help/sl/gedit/gedit-search.page
/usr/share/help/sl/gedit/gedit-shortcut-keys.page
/usr/share/help/sl/gedit/gedit-spellcheck.page
/usr/share/help/sl/gedit/gedit-syntax-highlighting.page
/usr/share/help/sl/gedit/gedit-tab-groups.page
/usr/share/help/sl/gedit/gedit-tabs-moving.page
/usr/share/help/sl/gedit/gedit-tabs.page
/usr/share/help/sl/gedit/gedit-undo-recent-action.page
/usr/share/help/sl/gedit/index.page
/usr/share/help/sl/gedit/legal.xml
/usr/share/help/sv/gedit/figures/gedit-html-snippet.png
/usr/share/help/sv/gedit/figures/gedit-icon.png
/usr/share/help/sv/gedit/figures/gedit3-screenshot.png
/usr/share/help/sv/gedit/gedit-change-color-scheme.page
/usr/share/help/sv/gedit/gedit-change-default-font.page
/usr/share/help/sv/gedit/gedit-close-file.page
/usr/share/help/sv/gedit/gedit-create-new-file.page
/usr/share/help/sv/gedit/gedit-edit-as-root.page
/usr/share/help/sv/gedit/gedit-files-basic.page
/usr/share/help/sv/gedit/gedit-full-screen.page
/usr/share/help/sv/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/sv/gedit/gedit-open-files.page
/usr/share/help/sv/gedit/gedit-open-on-server.page
/usr/share/help/sv/gedit/gedit-open-recent.page
/usr/share/help/sv/gedit/gedit-plugin-guide.page
/usr/share/help/sv/gedit/gedit-plugins-change-case.page
/usr/share/help/sv/gedit/gedit-plugins-doc-stats.page
/usr/share/help/sv/gedit/gedit-plugins-external-tools.page
/usr/share/help/sv/gedit/gedit-plugins-file-browser.page
/usr/share/help/sv/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/sv/gedit/gedit-plugins-install.page
/usr/share/help/sv/gedit/gedit-plugins-modelines.page
/usr/share/help/sv/gedit/gedit-plugins-pyconsole.page
/usr/share/help/sv/gedit/gedit-plugins-quick-open.page
/usr/share/help/sv/gedit/gedit-plugins-snippets.page
/usr/share/help/sv/gedit/gedit-plugins-sort.page
/usr/share/help/sv/gedit/gedit-printing-order.page
/usr/share/help/sv/gedit/gedit-printing-select.page
/usr/share/help/sv/gedit/gedit-printing.page
/usr/share/help/sv/gedit/gedit-quickstart.page
/usr/share/help/sv/gedit/gedit-replace.page
/usr/share/help/sv/gedit/gedit-save-file.page
/usr/share/help/sv/gedit/gedit-search.page
/usr/share/help/sv/gedit/gedit-shortcut-keys.page
/usr/share/help/sv/gedit/gedit-spellcheck.page
/usr/share/help/sv/gedit/gedit-syntax-highlighting.page
/usr/share/help/sv/gedit/gedit-tab-groups.page
/usr/share/help/sv/gedit/gedit-tabs-moving.page
/usr/share/help/sv/gedit/gedit-tabs.page
/usr/share/help/sv/gedit/gedit-undo-recent-action.page
/usr/share/help/sv/gedit/index.page
/usr/share/help/sv/gedit/legal.xml
/usr/share/help/te/gedit/figures/gedit-html-snippet.png
/usr/share/help/te/gedit/figures/gedit-icon.png
/usr/share/help/te/gedit/figures/gedit3-screenshot.png
/usr/share/help/te/gedit/gedit-change-color-scheme.page
/usr/share/help/te/gedit/gedit-change-default-font.page
/usr/share/help/te/gedit/gedit-close-file.page
/usr/share/help/te/gedit/gedit-create-new-file.page
/usr/share/help/te/gedit/gedit-edit-as-root.page
/usr/share/help/te/gedit/gedit-files-basic.page
/usr/share/help/te/gedit/gedit-full-screen.page
/usr/share/help/te/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/te/gedit/gedit-open-files.page
/usr/share/help/te/gedit/gedit-open-on-server.page
/usr/share/help/te/gedit/gedit-open-recent.page
/usr/share/help/te/gedit/gedit-plugin-guide.page
/usr/share/help/te/gedit/gedit-plugins-change-case.page
/usr/share/help/te/gedit/gedit-plugins-doc-stats.page
/usr/share/help/te/gedit/gedit-plugins-external-tools.page
/usr/share/help/te/gedit/gedit-plugins-file-browser.page
/usr/share/help/te/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/te/gedit/gedit-plugins-install.page
/usr/share/help/te/gedit/gedit-plugins-modelines.page
/usr/share/help/te/gedit/gedit-plugins-pyconsole.page
/usr/share/help/te/gedit/gedit-plugins-quick-open.page
/usr/share/help/te/gedit/gedit-plugins-snippets.page
/usr/share/help/te/gedit/gedit-plugins-sort.page
/usr/share/help/te/gedit/gedit-printing-order.page
/usr/share/help/te/gedit/gedit-printing-select.page
/usr/share/help/te/gedit/gedit-printing.page
/usr/share/help/te/gedit/gedit-quickstart.page
/usr/share/help/te/gedit/gedit-replace.page
/usr/share/help/te/gedit/gedit-save-file.page
/usr/share/help/te/gedit/gedit-search.page
/usr/share/help/te/gedit/gedit-shortcut-keys.page
/usr/share/help/te/gedit/gedit-spellcheck.page
/usr/share/help/te/gedit/gedit-syntax-highlighting.page
/usr/share/help/te/gedit/gedit-tab-groups.page
/usr/share/help/te/gedit/gedit-tabs-moving.page
/usr/share/help/te/gedit/gedit-tabs.page
/usr/share/help/te/gedit/gedit-undo-recent-action.page
/usr/share/help/te/gedit/index.page
/usr/share/help/te/gedit/legal.xml
/usr/share/help/th/gedit/figures/gedit-html-snippet.png
/usr/share/help/th/gedit/figures/gedit-icon.png
/usr/share/help/th/gedit/figures/gedit3-screenshot.png
/usr/share/help/th/gedit/gedit-change-color-scheme.page
/usr/share/help/th/gedit/gedit-change-default-font.page
/usr/share/help/th/gedit/gedit-close-file.page
/usr/share/help/th/gedit/gedit-create-new-file.page
/usr/share/help/th/gedit/gedit-edit-as-root.page
/usr/share/help/th/gedit/gedit-files-basic.page
/usr/share/help/th/gedit/gedit-full-screen.page
/usr/share/help/th/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/th/gedit/gedit-open-files.page
/usr/share/help/th/gedit/gedit-open-on-server.page
/usr/share/help/th/gedit/gedit-open-recent.page
/usr/share/help/th/gedit/gedit-plugin-guide.page
/usr/share/help/th/gedit/gedit-plugins-change-case.page
/usr/share/help/th/gedit/gedit-plugins-doc-stats.page
/usr/share/help/th/gedit/gedit-plugins-external-tools.page
/usr/share/help/th/gedit/gedit-plugins-file-browser.page
/usr/share/help/th/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/th/gedit/gedit-plugins-install.page
/usr/share/help/th/gedit/gedit-plugins-modelines.page
/usr/share/help/th/gedit/gedit-plugins-pyconsole.page
/usr/share/help/th/gedit/gedit-plugins-quick-open.page
/usr/share/help/th/gedit/gedit-plugins-snippets.page
/usr/share/help/th/gedit/gedit-plugins-sort.page
/usr/share/help/th/gedit/gedit-printing-order.page
/usr/share/help/th/gedit/gedit-printing-select.page
/usr/share/help/th/gedit/gedit-printing.page
/usr/share/help/th/gedit/gedit-quickstart.page
/usr/share/help/th/gedit/gedit-replace.page
/usr/share/help/th/gedit/gedit-save-file.page
/usr/share/help/th/gedit/gedit-search.page
/usr/share/help/th/gedit/gedit-shortcut-keys.page
/usr/share/help/th/gedit/gedit-spellcheck.page
/usr/share/help/th/gedit/gedit-syntax-highlighting.page
/usr/share/help/th/gedit/gedit-tab-groups.page
/usr/share/help/th/gedit/gedit-tabs-moving.page
/usr/share/help/th/gedit/gedit-tabs.page
/usr/share/help/th/gedit/gedit-undo-recent-action.page
/usr/share/help/th/gedit/index.page
/usr/share/help/th/gedit/legal.xml
/usr/share/help/uk/gedit/figures/gedit-html-snippet.png
/usr/share/help/uk/gedit/figures/gedit-icon.png
/usr/share/help/uk/gedit/figures/gedit3-screenshot.png
/usr/share/help/uk/gedit/gedit-change-color-scheme.page
/usr/share/help/uk/gedit/gedit-change-default-font.page
/usr/share/help/uk/gedit/gedit-close-file.page
/usr/share/help/uk/gedit/gedit-create-new-file.page
/usr/share/help/uk/gedit/gedit-edit-as-root.page
/usr/share/help/uk/gedit/gedit-files-basic.page
/usr/share/help/uk/gedit/gedit-full-screen.page
/usr/share/help/uk/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/uk/gedit/gedit-open-files.page
/usr/share/help/uk/gedit/gedit-open-on-server.page
/usr/share/help/uk/gedit/gedit-open-recent.page
/usr/share/help/uk/gedit/gedit-plugin-guide.page
/usr/share/help/uk/gedit/gedit-plugins-change-case.page
/usr/share/help/uk/gedit/gedit-plugins-doc-stats.page
/usr/share/help/uk/gedit/gedit-plugins-external-tools.page
/usr/share/help/uk/gedit/gedit-plugins-file-browser.page
/usr/share/help/uk/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/uk/gedit/gedit-plugins-install.page
/usr/share/help/uk/gedit/gedit-plugins-modelines.page
/usr/share/help/uk/gedit/gedit-plugins-pyconsole.page
/usr/share/help/uk/gedit/gedit-plugins-quick-open.page
/usr/share/help/uk/gedit/gedit-plugins-snippets.page
/usr/share/help/uk/gedit/gedit-plugins-sort.page
/usr/share/help/uk/gedit/gedit-printing-order.page
/usr/share/help/uk/gedit/gedit-printing-select.page
/usr/share/help/uk/gedit/gedit-printing.page
/usr/share/help/uk/gedit/gedit-quickstart.page
/usr/share/help/uk/gedit/gedit-replace.page
/usr/share/help/uk/gedit/gedit-save-file.page
/usr/share/help/uk/gedit/gedit-search.page
/usr/share/help/uk/gedit/gedit-shortcut-keys.page
/usr/share/help/uk/gedit/gedit-spellcheck.page
/usr/share/help/uk/gedit/gedit-syntax-highlighting.page
/usr/share/help/uk/gedit/gedit-tab-groups.page
/usr/share/help/uk/gedit/gedit-tabs-moving.page
/usr/share/help/uk/gedit/gedit-tabs.page
/usr/share/help/uk/gedit/gedit-undo-recent-action.page
/usr/share/help/uk/gedit/index.page
/usr/share/help/uk/gedit/legal.xml
/usr/share/help/zh_CN/gedit/figures/gedit-html-snippet.png
/usr/share/help/zh_CN/gedit/figures/gedit-icon.png
/usr/share/help/zh_CN/gedit/figures/gedit3-screenshot.png
/usr/share/help/zh_CN/gedit/gedit-change-color-scheme.page
/usr/share/help/zh_CN/gedit/gedit-change-default-font.page
/usr/share/help/zh_CN/gedit/gedit-close-file.page
/usr/share/help/zh_CN/gedit/gedit-create-new-file.page
/usr/share/help/zh_CN/gedit/gedit-edit-as-root.page
/usr/share/help/zh_CN/gedit/gedit-files-basic.page
/usr/share/help/zh_CN/gedit/gedit-full-screen.page
/usr/share/help/zh_CN/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/zh_CN/gedit/gedit-open-files.page
/usr/share/help/zh_CN/gedit/gedit-open-on-server.page
/usr/share/help/zh_CN/gedit/gedit-open-recent.page
/usr/share/help/zh_CN/gedit/gedit-plugin-guide.page
/usr/share/help/zh_CN/gedit/gedit-plugins-change-case.page
/usr/share/help/zh_CN/gedit/gedit-plugins-doc-stats.page
/usr/share/help/zh_CN/gedit/gedit-plugins-external-tools.page
/usr/share/help/zh_CN/gedit/gedit-plugins-file-browser.page
/usr/share/help/zh_CN/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/zh_CN/gedit/gedit-plugins-install.page
/usr/share/help/zh_CN/gedit/gedit-plugins-modelines.page
/usr/share/help/zh_CN/gedit/gedit-plugins-pyconsole.page
/usr/share/help/zh_CN/gedit/gedit-plugins-quick-open.page
/usr/share/help/zh_CN/gedit/gedit-plugins-snippets.page
/usr/share/help/zh_CN/gedit/gedit-plugins-sort.page
/usr/share/help/zh_CN/gedit/gedit-printing-order.page
/usr/share/help/zh_CN/gedit/gedit-printing-select.page
/usr/share/help/zh_CN/gedit/gedit-printing.page
/usr/share/help/zh_CN/gedit/gedit-quickstart.page
/usr/share/help/zh_CN/gedit/gedit-replace.page
/usr/share/help/zh_CN/gedit/gedit-save-file.page
/usr/share/help/zh_CN/gedit/gedit-search.page
/usr/share/help/zh_CN/gedit/gedit-shortcut-keys.page
/usr/share/help/zh_CN/gedit/gedit-spellcheck.page
/usr/share/help/zh_CN/gedit/gedit-syntax-highlighting.page
/usr/share/help/zh_CN/gedit/gedit-tab-groups.page
/usr/share/help/zh_CN/gedit/gedit-tabs-moving.page
/usr/share/help/zh_CN/gedit/gedit-tabs.page
/usr/share/help/zh_CN/gedit/gedit-undo-recent-action.page
/usr/share/help/zh_CN/gedit/index.page
/usr/share/help/zh_CN/gedit/legal.xml
/usr/share/help/zh_HK/gedit/figures/gedit-html-snippet.png
/usr/share/help/zh_HK/gedit/figures/gedit-icon.png
/usr/share/help/zh_HK/gedit/figures/gedit3-screenshot.png
/usr/share/help/zh_HK/gedit/gedit-change-color-scheme.page
/usr/share/help/zh_HK/gedit/gedit-change-default-font.page
/usr/share/help/zh_HK/gedit/gedit-close-file.page
/usr/share/help/zh_HK/gedit/gedit-create-new-file.page
/usr/share/help/zh_HK/gedit/gedit-edit-as-root.page
/usr/share/help/zh_HK/gedit/gedit-files-basic.page
/usr/share/help/zh_HK/gedit/gedit-full-screen.page
/usr/share/help/zh_HK/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/zh_HK/gedit/gedit-open-files.page
/usr/share/help/zh_HK/gedit/gedit-open-on-server.page
/usr/share/help/zh_HK/gedit/gedit-open-recent.page
/usr/share/help/zh_HK/gedit/gedit-plugin-guide.page
/usr/share/help/zh_HK/gedit/gedit-plugins-change-case.page
/usr/share/help/zh_HK/gedit/gedit-plugins-doc-stats.page
/usr/share/help/zh_HK/gedit/gedit-plugins-external-tools.page
/usr/share/help/zh_HK/gedit/gedit-plugins-file-browser.page
/usr/share/help/zh_HK/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/zh_HK/gedit/gedit-plugins-install.page
/usr/share/help/zh_HK/gedit/gedit-plugins-modelines.page
/usr/share/help/zh_HK/gedit/gedit-plugins-pyconsole.page
/usr/share/help/zh_HK/gedit/gedit-plugins-quick-open.page
/usr/share/help/zh_HK/gedit/gedit-plugins-snippets.page
/usr/share/help/zh_HK/gedit/gedit-plugins-sort.page
/usr/share/help/zh_HK/gedit/gedit-printing-order.page
/usr/share/help/zh_HK/gedit/gedit-printing-select.page
/usr/share/help/zh_HK/gedit/gedit-printing.page
/usr/share/help/zh_HK/gedit/gedit-quickstart.page
/usr/share/help/zh_HK/gedit/gedit-replace.page
/usr/share/help/zh_HK/gedit/gedit-save-file.page
/usr/share/help/zh_HK/gedit/gedit-search.page
/usr/share/help/zh_HK/gedit/gedit-shortcut-keys.page
/usr/share/help/zh_HK/gedit/gedit-spellcheck.page
/usr/share/help/zh_HK/gedit/gedit-syntax-highlighting.page
/usr/share/help/zh_HK/gedit/gedit-tab-groups.page
/usr/share/help/zh_HK/gedit/gedit-tabs-moving.page
/usr/share/help/zh_HK/gedit/gedit-tabs.page
/usr/share/help/zh_HK/gedit/gedit-undo-recent-action.page
/usr/share/help/zh_HK/gedit/index.page
/usr/share/help/zh_HK/gedit/legal.xml
/usr/share/help/zh_TW/gedit/figures/gedit-html-snippet.png
/usr/share/help/zh_TW/gedit/figures/gedit-icon.png
/usr/share/help/zh_TW/gedit/figures/gedit3-screenshot.png
/usr/share/help/zh_TW/gedit/gedit-change-color-scheme.page
/usr/share/help/zh_TW/gedit/gedit-change-default-font.page
/usr/share/help/zh_TW/gedit/gedit-close-file.page
/usr/share/help/zh_TW/gedit/gedit-create-new-file.page
/usr/share/help/zh_TW/gedit/gedit-edit-as-root.page
/usr/share/help/zh_TW/gedit/gedit-files-basic.page
/usr/share/help/zh_TW/gedit/gedit-full-screen.page
/usr/share/help/zh_TW/gedit/gedit-open-files-from-sidepane.page
/usr/share/help/zh_TW/gedit/gedit-open-files.page
/usr/share/help/zh_TW/gedit/gedit-open-on-server.page
/usr/share/help/zh_TW/gedit/gedit-open-recent.page
/usr/share/help/zh_TW/gedit/gedit-plugin-guide.page
/usr/share/help/zh_TW/gedit/gedit-plugins-change-case.page
/usr/share/help/zh_TW/gedit/gedit-plugins-doc-stats.page
/usr/share/help/zh_TW/gedit/gedit-plugins-external-tools.page
/usr/share/help/zh_TW/gedit/gedit-plugins-file-browser.page
/usr/share/help/zh_TW/gedit/gedit-plugins-insert-date-time.page
/usr/share/help/zh_TW/gedit/gedit-plugins-install.page
/usr/share/help/zh_TW/gedit/gedit-plugins-modelines.page
/usr/share/help/zh_TW/gedit/gedit-plugins-pyconsole.page
/usr/share/help/zh_TW/gedit/gedit-plugins-quick-open.page
/usr/share/help/zh_TW/gedit/gedit-plugins-snippets.page
/usr/share/help/zh_TW/gedit/gedit-plugins-sort.page
/usr/share/help/zh_TW/gedit/gedit-printing-order.page
/usr/share/help/zh_TW/gedit/gedit-printing-select.page
/usr/share/help/zh_TW/gedit/gedit-printing.page
/usr/share/help/zh_TW/gedit/gedit-quickstart.page
/usr/share/help/zh_TW/gedit/gedit-replace.page
/usr/share/help/zh_TW/gedit/gedit-save-file.page
/usr/share/help/zh_TW/gedit/gedit-search.page
/usr/share/help/zh_TW/gedit/gedit-shortcut-keys.page
/usr/share/help/zh_TW/gedit/gedit-spellcheck.page
/usr/share/help/zh_TW/gedit/gedit-syntax-highlighting.page
/usr/share/help/zh_TW/gedit/gedit-tab-groups.page
/usr/share/help/zh_TW/gedit/gedit-tabs-moving.page
/usr/share/help/zh_TW/gedit/gedit-tabs.page
/usr/share/help/zh_TW/gedit/gedit-undo-recent-action.page
/usr/share/help/zh_TW/gedit/index.page
/usr/share/help/zh_TW/gedit/legal.xml

%files lib
%defattr(-,root,root,-)
/usr/lib64/gedit/libgedit-3.14.so
/usr/lib64/gedit/plugins/libdocinfo.so
/usr/lib64/gedit/plugins/libfilebrowser.so
/usr/lib64/gedit/plugins/libmodelines.so
/usr/lib64/gedit/plugins/libquickhighlight.so
/usr/lib64/gedit/plugins/libsort.so
/usr/lib64/gedit/plugins/libspell.so
/usr/lib64/gedit/plugins/libtime.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/gedit/gedit-bugreport.sh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gedit/COPYING
/usr/share/package-licenses/gedit/win32_installer_COPYING.rtf

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gedit.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f gedit.lang
%defattr(-,root,root,-)

